version: "3"

services:
  dnote:
    image: dnote/dnote:latest
    environment:
      APP_ENV: PRODUCTION
      WebURL: localhost:3000
      DisableRegistration: "false"
    ports:
      - 3000:3000
    volumes:
      - ./dnote_data:/data
    restart: always
