name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version: '>=1.25.0'

      - name: Install dependencies
        run: |
          make install

      - name: Test cli
        run: |
          make test-cli

      - name: Test app
        run: |
          make test-api

      - name: Test e2e
        run: |
          make test-e2e
